project = "PseudoGame"
description = "A library giving greater control over game components and rendering"
full_description = "PseudoGame not only reimplements the game's components to look exactly as the original but also adds options to extend them. Furthermore it provides an advanced rendering system based on custom walls, that allows for all kinds of visual effects to be created."
title = "PseudoGame Documentation"
file = "Scripts"
format = "markdown"
style = true
template = true
