-- this script includes the libraries components for more convenient importing
u_execScript("graphics/polygon_collection.lua")
u_execScript("graphics/polygon.lua")
u_execScript("graphics/screen.lua")
u_execScript("graphics/cw_overwrite.lua")
u_execScript("graphics/transform.lua")
u_execScript("game/background.lua")
u_execScript("game/cap.lua")
u_execScript("game/colliding_player.lua")
u_execScript("game/death_effect.lua")
u_execScript("game/pivot.lua")
u_execScript("game/player.lua")
u_execScript("game/wall_system.lua")
u_execScript("game/init.lua")
