name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup luajit
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: luajit
      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Setup busted
        run: luarocks install busted
      - name: Run tests
        run: |
          cd tests
          luajit main.lua
